version: 2.1

references:
  container_config: &container_config
    docker:
      - image: circleci/node:12-browsers
    working_directory: ~/app

  restore_deps_cache: &restore_deps_cache
    restore_cache:
      keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-

  save_deps_cache: &save_deps_cache
    save_cache:
      key: v1-dependencies-{{ checksum "package.json" }}
      paths:
        - node_modules

  install_deps: &install_deps
    run:
      name: Install Dependencies
      command: npm install

jobs:
  test:
    <<: *container_config
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - *restore_deps_cache
      - *install_deps
      - *save_deps_cache
      - run:
          name: Build app
          command: make build
      - run:
          name: Run test
          command: npm test

workflows:
  default:
    jobs:
      - test
